Jenkins deploy script

diff --git a/jenkins-deploy b/jenkins-deploy
--- a/jenkins-deploy
+++ b/jenkins-deploy
@@ -12,9 +12,10 @@ node_modules/.bin/cosmos-deploy update-repositories digital-paper-edit-$DIR $ENV
 node_modules/.bin/cosmos-deploy update-config digital-paper-edit-$DIR $ENV 1.0.0 || echo "No config files"
 node_modules/.bin/cosmos-deploy provision-stack digital-paper-edit-$DIR $ENV 1.0.0 dns
 node_modules/.bin/cosmos-deploy provision-stack digital-paper-edit-$DIR $ENV 1.0.0 main
+node_modules/.bin/cosmos-deploy provision-stack digital-paper-edit-$DIR $ENV 1.0.0 monitoring || echo "Couldn't create log stack"; 
 
 if [ $DIR = "stt-proxy" ] || [ $DIR = "audio-converter" ] ; then
-    node_modules/.bin/cosmos-deploy provision-stack digital-paper-edit-$DIR $ENV 1.0.0 queue;
+    node_modules/.bin/cosmos-deploy provision-stack digital-paper-edit-$DIR $ENV 1.0.0 queue; 
 else
 	echo "Not a microservice, not provisioning queue"
 fi
